# Define jobs
jobs:
  include:
    # Run our custom Git commit checks
    - name: Gnitpick
      language: python
      services: # none
      install:
      - curl -O https://raw.githubusercontent.com/Seravo/gnitpick/master/gnitpick.py
      script:
      - python3 ./gnitpick.py
    # Sniff with some PHP version
    - php: '7.2'
      env: SNIFF=1
    # Test PHP 7.4
    - php: '7.4'
    # Test the PHP development version
    - php: 'nightly'
    # Test the WordPress development version
#    - php: '7.4'
#      env: WP_VERSION=nightly
    # Test the WooCommerce development version
    # Test the all development versions
    - php: '8.0'
      env: WOO_VERSION=nightly
    - php: '8.1'
    - php: 'nightly'
      env: WP_VERSION=nightly WOO_VERSION=nightly
  allow_failures:
    # WordPress core is currenlty not compatible with PHP 8,
    # so tests with the PHP development version will fail with:
    #   PHP Fatal error:  Uncaught RuntimeException: Array and string offset
    #   access syntax with curly braces is deprecated on line 757 in file
    #   /tmp/wordpress/wp-includes/script-loader.php
    - php: 7.4
    - php: nightly

# Common for all jobs
language: php
services: mysql

install:
  - ./tests/install-tests.sh
  # After CodeSniffer install you should refresh PHP paths on Travis-CI
  - phpenv rehash

script:
  # Use installed PHPCS and PHP Unit in custom locations instead of Travis defaults
  - ./tests/run-tests.sh
